#!/usr/bin/env ruby
require './random_presents_between_people.rb'
require './draw_associations_presenter.rb'

result = RandomPresentsBetweenPeople.new(ARGV.length).draw
DrawAssociationsPresenter.print(result, ARGV)
